language: php
os: linux
dist: xenial

env:
  global:
    - COMPOSER_MEMORY_LIMIT="-1"

jobs:
    include:
      - php: 7.2
      - php: 7.3
      - php: 7.4
        env: WITH_CS="true" RELEASE="true"

cache:
    directories:
      - $HOME/.composer/cache

install:
    - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS

before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer update --no-interaction --prefer-dist

script:
    - bin/phpunit
    - if [[ "$WITH_CS" == "true" ]]; then bin/paysera-php-cs-fixer fix --config=.php_cs -v --dry-run --stop-on-violation --using-cache=no --path-mode=intersection "${COMMIT_SCA_FILES[@]}"; fi
    - if [[ "$RELEASE" == "true" ]]; then composer run compile; fi

deploy:
    provider: releases
    token:
        secure: "Kv1O1dOayeqMiybQAYd1E+hXYTKPZcE0sU2FUXe4NO1WdUX8BfqDqzbGJxFcUPCCUyIpzpv18MLZIctRKo0/TR1YXIGL3PK46agL/SxuELOKS+UwCXxaQBKBzkzyFAgUaY0vFioA/rLqORlZnggiYJfuJ8Uh3JtHP/fBoQK1cJj7VP3pV46iMtcMixRSMoSxndJzqgUqAKxeoTzI858nXcTmmd6fQ5cRRAygBDNSmlyATQ7fwX6wUMVODqtjJnKaIQUySMKvFemNUfnT2LjUpEPFiW5NfVu7ZFPohniZRrbWR//cufvnjuw2gfoSzDRm50E8eKJYHhNwV0JxY/EsBdo9kcEBoL7+AeTZr1rddlyuPTPcBebVf8ua+hHbB54qFwyW6AFi9vXLXg806qH2qdzkxdZ7ePeZOHvLL/yJJBwtcXcIe9yirzp5oMJJTTv/CPZH8y2NzNo+d++MXWaYdcnd5XyEAU/FoG1m9FNPX2LZcbVFqRIIBgjAmfNspoUNZtVqR+2xIjgkMoj5VVKmEnaJ3qLCDmQqWLYGzQjXXEla99YvEoN1rG4gNdJ3xU+M9MhrIf0R3mRNrUl0HNEE2CSOE4z7/iltOzqzpdZJKG8pJsU7X0x40urLj/7uPyBiRSqufhdrhNCjhrOU8IX5rf8HvR1EnX/uJQ6nupfb6Ok="
    file: bin/phpstorm-helper.phar
    on:
        repo: paysera/util-phpstorm-helper
        tags: true
        condition: "$RELEASE"
    skip_cleanup: true
