#!/usr/bin/env php
<?php
declare(strict_types=1);

use Paysera\PhpStormHelper\PhpStormHelperApplication;

// check for pdepend installed as composer package
if (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

$application = new PhpStormHelperApplication();

$application->run();
